Problem Statement:<br>
<a href="https://www.hackerearth.com/challenges/competitive/hackerearth-machine-learning-challenge-predict-the-lowest-price/problems/">Slashing prices for the biggest sale day</a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
%cd "/content/drive/My Drive/Colab_Notebooks/HackerEarth Slacing Prices for the biggest sale day"
train = pd.read_csv("Train.csv")
test = pd.read_csv("Test.csv")

[WinError 3] The system cannot find the path specified: '/content/drive/My Drive/Colab_Notebooks/HackerEarth Slacing Prices for the biggest sale day'
U:\HackerEarth Slacing Prices for the biggest sale day


In [3]:
train.head()

Item_Id        Date  State_of_Country  Market_Category  Product_Category  \
0    IT_1  2007-07-05                 0                0                 0   
1    IT_2  2007-07-05                 0                1                 0   
2    IT_3  2007-07-05                 0              103                 0   
3    IT_4  2007-07-05                 0              103                 0   
4    IT_5  2007-07-05                 0              103                 0   

   Grade  Demand  Low_Cap_Price  High_Cap_Price  
0      0     0.5           2785            4240  
1      0     0.7           3574            4756  
2      1     1.6           5978            9669  
3      0     0.0           5681            8313  
4      2     0.0           4924            7257

In [4]:
test.head()

Item_Id        Date  State_of_Country  Market_Category  Product_Category  \
0  IT_265079  2014-01-19                 0                3                 0   
1  IT_265087  2014-01-19                 0              268                 0   
2  IT_265107  2014-01-19                 0              320                 0   
3  IT_265139  2014-01-19                17              358                 0   
4  IT_265142  2014-01-19                18               23                 5   

   Grade  Demand  High_Cap_Price  
0      0     0.1            5303  
1      2     1.4           10492  
2      0    13.4           24706  
3      3     5.5           23464  
4      2     0.0            6222

In [5]:
# Changing the type
train['Demand'] = train['Demand'].astype('int64')
test['Demand'] = test['Demand'].astype('int64')

In [6]:
# dropping columns
X_train = train.drop(['Item_Id', 'Date', 'Low_Cap_Price'],axis = 1)
X_train.columns

Index(['State_of_Country', 'Market_Category', 'Product_Category', 'Grade',
       'Demand', 'High_Cap_Price'],
      dtype='object')

In [7]:
X_test = test.drop(['Item_Id', 'Date'], axis = 1)
X_test.columns

Index(['State_of_Country', 'Market_Category', 'Product_Category', 'Grade',
       'Demand', 'High_Cap_Price'],
      dtype='object')

In [8]:
# Setting the predict variable here and the shape
y_train = train['Low_Cap_Price']

In [9]:
X_train.shape

(9798, 6)

#Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
preds = clf.predict(X_test)
preds


array([ 2418.53967135,  4100.02927888, 11192.73258092, ...,
        5913.77916699,  5293.24905298,  6569.9374812 ])

In [12]:
submission = pd.DataFrame({'Item_Id':test['Item_Id'], 'Low_Cap_Price':preds})
submission.to_csv('SubmissionFileLF.csv', index=False)

# Random Forest Regressor

In [13]:
from sklearn.ensemble import RandomForestRegressor
clf2 = RandomForestRegressor(bootstrap= True,max_depth=10, max_features=6, n_estimators=400,min_samples_leaf=6
                             ,min_samples_split=12, random_state=10,ccp_alpha=0,n_jobs=-1) 
clf2.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0, criterion='mse',
                      max_depth=10, max_features=6, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=6,
                      min_samples_split=12, min_weight_fraction_leaf=0.0,
                      n_estimators=400, n_jobs=-1, oob_score=False,
                      random_state=10, verbose=0, warm_start=False)

In [14]:
preds2 = clf2.predict(X_test)
preds2

array([3202.2141618 , 2844.18582316, 5728.89556476, ..., 6573.06454377,
       5385.94048123, 7425.8844049 ])

In [15]:
submission = pd.DataFrame({'Item_Id':test['Item_Id'], 'Low_Cap_Price':preds2})
submission.to_csv('SubmissionFileRF.csv', index=False)

#Standard Scaler

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)
rescaled_X_train = scaler.transform(X_train)

#KNN

In [17]:
from sklearn.neighbors import KNeighborsRegressor
clf3 = KNeighborsRegressor(algorithm='brute')

clf3.fit(X_train,y_train)

KNeighborsRegressor(algorithm='brute', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [18]:
preds3 = clf3.predict(X_test)
preds3

array([3615.4, 3731. , 8944. , ..., 7283.6, 5817.4, 6286.4])

In [19]:
submission = pd.DataFrame({'Item_Id':test['Item_Id'], 'Low_Cap_Price':preds3})
submission.to_csv('SubmissionFile.csv', index=False)

#SVR

In [20]:
from sklearn.svm import SVR
from sklearn import preprocessing
X_train = preprocessing.scale(X_train)
X_test = preprocessing.scale(X_test)
clf4 = SVR(kernel = 'linear')
clf4.fit(X_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [21]:
preds4 = clf4.predict(X_test)
preds4

array([2674.79187602, 2053.85248516, 2962.84122812, ..., 4263.59202948,
       4331.09059953, 4191.18433159])

In [22]:
submission = pd.DataFrame({'Item_Id':test['Item_Id'], 'Low_Cap_Price':preds4})
submission.to_csv('SubmissionFileSVR.csv', index=False)

#Selecting Best Parameters

In [23]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [10,50,80, 90, 100, 110],
    'max_features': [2, 3,5,6],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200,400, 300, 1000]
}
# Create a based model
rf = RandomForestRegressor()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 10, n_jobs = -1, verbose = 2)

In [ ]:
grid_search.fit(X_train, y_train)

Fitting 10 folds for each of 1080 candidates, totalling 10800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   24.5s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  6.7min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed: 13.2min


In [ ]:
grid_search.best_params_
#run it again and again for different results

In [ ]:
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor(bootstrap= True,max_depth=10, max_features=3, n_estimators=400,min_samples_leaf=5
                             ,min_samples_split=12, random_state=10) 
clf.fit(X_train,y_train)


In [ ]:
from sklearn.ensemble import RandomForestRegressor
clf2 = RandomForestRegressor(bootstrap= True,max_depth=10, max_features=6, n_estimators=400,min_samples_leaf=5
                             ,min_samples_split=12, random_state=10) 
clf2.fit(X_train,y_train)

#This got me 99.84988

<h3>Reference:</h3>
<a href="https://github.com/AmitHasanShuvo/Machine-Learning-Competitions/blob/master/HackerEarth%20Machine%20Learning%20challenge%20Slashing%20prices%20for%20the%20biggest%20sale%20day/Slashing%20the%20price.ipynb">amithasanshuvo</a>